spring.application.name=oauth2_GITUHB
spring.security.oauth2.client.registration.github.client-id=Ov23lirNuEGpSBSdNl1v
spring.security.oauth2.client.registration.github.client-secret=4922802a4246b99f1db0616df1ce88ceeda7e159
